### ISSUE TITLE
Set default: true is not idempotent

### ISSUE THREAD

**Issue by morgangraphics** [morgangraphics/ansible-role-nvm#36]
```yaml
- hosts: foo
  roles:
    - role: ansible-role-nvm
      nodejs_version: "8.15.0"

    - role: ansible-role-nvm
      nodejs_version: "10.15.0"
      default: true
```

triggers a change when run multiple times and is not idempotent.
